language: node_js
node_js:
  - "6"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: "dist/production"
  # local_dir: "dist/development"

cache:
  directories:
    - node_modules
  yarn: true

script:
  # - true
  - "yarn run build:prod"
  # - "yarn run build:dev"
  - "yarn run test:travis"


