export const ADD_PROJECT = 'ADD_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';

export const OPEN_CLOSE_PROJECT = 'OPEN_CLOSE_PROJECT';

export const ADD_VACANCY = 'ADD_VACANCY';
export const REMOVE_VACANCY = 'REMOVE_VACANCY';

export const OPEN_CLOSE_VACANCY = 'OPEN_CLOSE_VACANCY';
