export const ADD_PROJECT = 'ADD_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';

export const CLOSE_PROJECT = 'CLOSE_PROJECT';
export const REFRESH_PROJECT = 'REFRESH_PROJECT';

export const ADD_VACANCY = 'ADD_VACANCY';
export const REMOVE_VACANCY = 'REMOVE_VACANCY';

export const CLOSE_VACANCY = 'CLOSE_VACANCY';
export const REFRESH_VACANCY = 'REFRESH_VACANCY';
